---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: app-ns-stage
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: testapp.eger.pro
    http:
      paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: appservice
              port:
                name: web-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: grafana-ingress
  labels:
    app.kubernetes.io/component: grafana
    app.kubernetes.io/name: grafana
    app.kubernetes.io/part-of: kube-prometheus
    app.kubernetes.io/version: 9.2.3
  namespace: monitoring
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: grafana.eger.pro
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: grafana-ingress
              port:
                 number: 3000
